"""telemetry and alerts

Revision ID: 8863f258cbfe
Revises: 7fc241ca903f
Create Date: 2026-08-07 18:27:13.677741

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8863f258cbfe"
down_revision: str | Sequence[str] | None = "7fc241ca903f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("message", sa.String(length=240), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_alerts_device_type_open",
        "alerts",
        ["device_id", "type"],
        unique=True,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.create_table(
        "telemetry",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("battery_pct", sa.Float(), nullable=False),
        sa.Column("temp_c", sa.Float(), nullable=False),
        sa.Column("signal_rssi", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_telemetry_device_ts", "telemetry", ["device_id", "ts"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_telemetry_device_ts", table_name="telemetry")
    op.drop_table("telemetry")
    op.drop_index(
        "ix_alerts_device_type_open",
        table_name="alerts",
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.drop_table("alerts")
    # ### end Alembic commands ###
